toyproject/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup')
]

toyproject/mainapp/urls.py
from django.contrib import admin
from django.urls import path
# from mainapp.views import * # from .views import *
from .views import base_views, question_views, answer_views

# 이미지 업로드
from django.conf.urls.static import static
from django.conf import settings

app_name='mainapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    # # 웹사이트의 첫화면은 index 페이지이다 + URL이름은 index (별칭)
    # # path('', index, name='index'),
    # # URL:80/blog에 접속하면 blog 페이지 + URL이름은 blog 
    # path('blog/', blog, name='blog'),
    # # URL:80/blog/숫자로 접속하면 게시글-세부페이지(posting)
    # path('blog/<int:pk>/', posting, name="posting"),
    # # 글쓰기 페이지 추가
    # path('blog/new_post/', new_post),
    # # 삭제 페이지 추가
    # path('blog/<int:pk>/remove/', remove_post),
    
    # # 영화_로그인 페이지 추가
    # path('movie_login/', movie_login, name='movie_login'),

    # Q&A 페이지 추가 
    path('', base_views.qna_main, name='qna_main'),
    path('qna_main/', base_views.qna_main, name='qna_main'),
    path('qna_main/<int:pk>/', base_views.qna_detail, name='qna_detail'),

    path('qna_main/question/create/', question_views.question_create, name='question_create'),
    path('qna_main/question/modify/<int:pk>/', question_views.question_modify, name='question_modify'),
    path('qna_main/question/delete/<int:pk>/', question_views.question_delete, name='question_delete'),
    path('qna_main/question/vote/<int:pk>/', question_views.question_vote, name='question_vote'),

    path('qna_main/answer/create/<int:pk>/', answer_views.answer_create, name='answer_create'),
    path('qna_main/answer/modify/<int:pk>/', answer_views.answer_modify, name='answer_modify'),
    path('qna_main/answer/delete/<int:pk>/', answer_views.answer_delete, name='answer_delete'),
    path('qna_main/answer/vote/<int:pk>/', answer_views.answer_vote, name='answer_vote'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toyproject/toyproject/urls.py
from django.contrib import admin
from django.urls import include, path
from mainapp.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")), # 기본 url -> mainapp
    path("common/", include("common.urls")),
    # path("", base_views.qna_main, name='mainapp'),
]

toyproject/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# 게시글(Post) 클래스 - 제목(postname), 내용(contents)
# 일반적으로 models.py를 수정했다면 바로 migrate 해서 db에 저장
class Post(models.Model):
    postname = models.CharField(max_length=50)
    mainphoto = models.ImageField(blank=True, null=True) # blank=True : don't need input/ null=True : Nullable in db
    contents = models.TextField()

    # 게시글의 제목(postname)이 Post object 대신하기
    def __str__(self):
        return self.postname
    
# Q&A 페이지 모델
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question') # 특정 사용자가 작성한 질문 접근 : userkey.author_question.all()
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True) # 수정한 경우에만 생성되는 데이터이므로, 값이 없어도 됨.
    voter = models.ManyToManyField(User, related_name='voter_question') # 추천인/ # 특정 사용자가 추천한 질문 접근 : userkey.voter_question.all()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True) # 수정한 경우에만 생성되는 데이터이므로, 값이 없어도 됨.
    voter=models.ManyToManyField(User, related_name='voter_answer')

toyproject/mainapp/forms.py
from django import forms
from mainapp.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        # }
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

toyproject/mainapp/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('mainapp:qna_detail', pk=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'mainapp/qna_detail.html', {'question':question})   

@login_required(login_url='common:login')
def answer_modify(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('mainapp:qna_detail', pk=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('mainapp:qna_detail', pk=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'mainapp/qna_answer.html', context)

@login_required(login_url='common:login')
def answer_delete(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('mainapp:qna_detail', pk=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 답변은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('mainapp:qna_detail', pk=answer.question.id), answer.id))

toyproject/mainapp/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question

def qna_main(request):
    page = request.GET.get('page', '1') # 페이지 값 가져오기 (default=1)
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()   
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    return render(request, 'mainapp/qna_main.html', {'question_list':page_obj, 'page':page, 'kw':kw})

def qna_detail(request, pk):
    question = get_object_or_404(Question, pk=pk) # Post.objects.filter(), Post.objects.get()
    return render(request, 'mainapp/qna_detail.html', {'question':question})

toyproject/mainapp/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('mainapp:qna_main')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'mainapp/qna_question.html', context)

@login_required(login_url='common:login')
def question_modify(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('mainapp:qna_detail', pk=question.id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('mainapp:qna_detail', pk=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'mainapp/qna_question.html', context)

@login_required(login_url='common:login')
def question_delete(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('mainapp:question_detail', pk=question.id)
    question.delete()
    return redirect('mainapp:qna_main')

@login_required(login_url='common:login')
def question_vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 질문은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('mainapp:qna_detail', pk=question.id)

toyproject/mainapp/templates/mainapp/blog.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/style_blog.css' %}">
        <title>Blog List</title>
    </head>
    <body>
        <h1>게시판 페이지입니다</h1>
        <!-- 게시판(postlist)의 게시글(list)을 하나씩 보여줍니다 -->
        <!-- {와 %로 이루어진 구문 내부엔 파이썬이 사용됩니다 -->
        <table>
        {% for list in postlist %}
            <!-- 게시글 클릭시 세부페이지로 넘어갑니다-->
            <ul class="postlist">
                <li><a href="{{list.pk}}/">{{list.postname}}</a></li> <!--<li> 태그에 <a> 태그를 넣어 이동할 수 있게 함--> 
            </ul>
        {% endfor %}
        </table>
        <button><a href="new_post/">글쓰기</a></button>
    </body>
</html>

toyproject/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    'This is Toy Project'
</body>
</html>

toyproject/mainapp/templates/mainapp/movie_login.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/style_movie_login.css' %}">
        <!-- <link rel=”stylesheet” href=”https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css”> -->
    </head>
    <div class="login-box">
        <h2>Login</h2>
        <form>
          <div class="user-box">
            <input type="text" name="" required="">
            <label>Username</label>
          </div>
          <div class="user-box">
            <input type="password" name="" required="">
            <label>Password</label>
          </div>
          <a href="#">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Submit
          </a>
        </form>
      </div>
</html>

toyproject/mainapp/templates/mainapp/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글쓰기 페이지</title>
</head>
<body>
    <h1>글쓰기 페이지</h1>
    <form method="POST"> <!--TAG 'form' : 내부의 정보를 한 번에 서버로 전송, method 'POST' : 정보를 서버에 전송하여 DB에 저장-->
        {% csrf_token %} <!--csrf : 사이트 간 요청 위조 -> 취약성 보완, form 태그 밑에 항상 위치해야 함.-->
        제목<br>
        <input type="text" name="postname"><br>
        내용<br>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input type="file" name="mainphoto"><br>
        <input type="submit" value="작성"> <!--buton clicked -> 정보를 서버로 전송-->
    </form>
</body>
</html>

toyproject/mainapp/templates/mainapp/posting.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_posting.css' %}">
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <h1>게시글 개별 페이지입니다</h1>
        <p>{{post.postname}}</p>
        <p>{{post.contents}}</p>
        <!-- 이미지 보여주기 -->
        {% if post.mainphoto %}
            <img src = "{{ post.mainphoto.url }}" alt="" height="600">
            <br>
        {% endif %}
        <button><a href="/blog/">게시판 목록</a></button>
        <button><a href="/blog/{{post.pk}}/remove">삭제</a></button>
    </body>
</html>

toyproject/mainapp/templates/mainapp/qna_answer.html
{% extends 'mainapp/qna_base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "common/form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

toyproject/mainapp/templates/mainapp/qna_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_qna_main.css' %}">
    <title>Q&A</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "mainapp/qna_navvar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

toyproject/mainapp/templates/mainapp/qna_detail.html
{% extends 'mainapp/qna_base.html' %}
{% load qna_filter %}
{% block content %}
<div class="container my-3">
     <!-- message 표시 -->
     {% if messages %}
     <div class="alert alert-danger my-3" role="alert">
     {% for message in messages %}
         <strong>{{ message.tags }}</strong>
         <ul><li>{{ message.message }}</li></ul>
     {% endfor %}
     </div>
     {% endif %}   
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">질문수정일시</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'mainapp:question_vote' question.id  %}"
                class="recommend btn btn-sm btn-outline-secondary"> 추천
                 <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
             </a>
                {% if request.user == question.author %} <!-- # 로그인된 사용자==작성자 인 경우 -->
                <a href="{% url 'mainapp:question_modify' question.id  %}" 
                   class="btn btn-sm btn-outline-secondary">질문 수정</a>
                   <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'mainapp:question_delete' question.id  %}">질문 삭제</a>
                {% endif %}
            </div>         
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">답변수정일시</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'mainapp:answer_vote' answer.id  %}"
                class="recommend btn btn-sm btn-outline-secondary"> 추천
                 <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'mainapp:answer_modify' answer.id  %}" 
                   class="btn btn-sm btn-outline-secondary">답변 수정</a>
                   <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'mainapp:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'mainapp:answer_create' question.id %}" method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

toyproject/mainapp/templates/mainapp/qna_main.html
{% extends 'mainapp/qna_base.html' %}
{% load qna_filter %}
<!-- {% load static %}
<link rel="stylesheet" href="{% static 'css/style_qna_main.css' %}">\ -->
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'mainapp:question_create' %}" class="btn btn-primary">질문 등록</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
            <th>No</th>
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="/qna_main/{{question.id}}/">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                href="javascript:void(0)">이전</a>
                <!-- <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a> -->
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)">다음</a>
                <!-- <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a> -->
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    <!-- <a href="{% url 'mainapp:question_create' %}", class="btn btn-primary">질문 등록</a> -->
</div>
<form id="searchForm" method="get" action="{% url 'mainapp:qna_main' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

toyproject/mainapp/templates/mainapp/qna_navvar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mainapp:qna_main' %}">Q&A</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

toyproject/mainapp/templates/mainapp/qna_question.html
{% extends 'mainapp/qna_base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

toyproject/mainapp/templates/mainapp/remove_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 삭제</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h3>{{ Post.postname }} - 삭제하기</h3>
        <button>삭제</button> <!--buton clicked -> 정보를 서버로 전송-->
    </form>
</body>
</html>